### PR TITLE
removing unnecessary zip file, adding contents

### PR DESCRIPTION
**Pull request by chabala**
It's a lot easier to browse the source when it's not in a binary blob. Perhaps this could be the standard going forward?

### CODE REVIEW

**Comment by chabala** [comment]
@robthez any thoughts on this? It's cool you're making repos for each MagPi issue, but a single zip file in each is not useful.
Linking to lines in the source, submitting patches and corrections, none of that works for binary blobs.

**Comment by robthez** [comment]
Ah Chabala, my apologies I didn't see this earlier - so the zip is there as it was requested by a few readers. Everything in the zip is provided as a repo either on our repo for the mags, or on the repo for the writers. You'll find links for them in the magazine.

This is not instead of source, it's in addition to.

Of course if there is a repo missing that is only in the zip, let me know and I can put it on the repo for the relevant mag.

**Comment by chabala** [comment]
I suppose I'm still a little confused. For instance, the zip for this issue 94 contains these folders/projects:
- 3D camera
- HQ Camera case hack
- Learn Java part 2

if these are represented as unzipped source elsewhere in other repositories, where? Can you link to them?

**Comment by robthez** [comment]
You'll find the links in their respective tutorials in the magazine:

3D Camera: magpi.cc/3dcameragit
HQ Camera: magpi.cc/hqchack

Looks like I should have done a repository for the Learn Java code though, that one is an error on my part! I'll get it added.

**Comment by chabala** [comment]
Ah, I see. Do you think these would be good links for the README in the base of the repo? Perhaps even direct links, without the magpi.cc redirector.

~~Also, why not let this repo be the repo of authority for the Learn Java project. No need for additional repos to track.~~ I see this is the case.

**Comment by robthez** [comment]
Sure, that's a good idea. I'll start doing it from the next magazine.

**Pull request closed without merging**
